### ISSUE TITLE
Update Readme.md file

### ISSUE THREAD

**Issue by crypticani** [crypticani/Data_Structures#12]
Many new programs have been added and organized in folders since last readme update.
You can update the readme file with the names of programs and hyperlinks to them in an organized manner.
You can also show your creativity here.
This issue is open to all.
The best one will be merged to the repo and marked as "hacktoberfest-accepted" label.
Note: make a PR only if you really want to contribute to this repo. Just slightly changing the file for a PR count will not be accepted and will be labelled as "invalid".

**Comment by TrevorAbram** [comment]
@crypticani Hey there, I would like to work on this if that's ok? Can you assign it to me?

**Comment by crypticani** [comment]
This issue is open to all. 
Just fork this repo, update the Readme and make a PR.

**Comment by TrevorAbram** [comment]
That I can do, thanks!

**Comment by TrevorAbram** [comment]
Thanks for approving the PR!

**Comment by crypticani** [comment]
You are welcome @TrevorAbram .
If it helped you in increasing your PR count for hacktoberfest, you can give a star to this repo.
